authors:
- Guillaume Jacquemet and the ZeroCostDL4Mic Team
badges:
- icon: https://colab.research.google.com/assets/colab-badge.svg
  label: Open in Colab
  url: https://colab.research.google.com/github/HenriquesLab/ZeroCostDL4Mic/blob/master/Colab_notebooks/DecoNoising_2D_ZeroCostDL4Mic.ipynb
cite:
- doi: https://doi.org/10.1038/s41467-021-22518-0
  text: von Chamier, L., Laine, R.F., Jukkala, J. et al. Democratising deep learning for microscopy with ZeroCostDL4Mic. Nat Commun 12, 2276 (2021). https://doi.org/10.1038/s41467-021-22518-0
- text: Anna S. Goncharova, Alf Honigmann, Florian Jug, Alexander Krull. Improving Blind Spot Denoising for Microscopy. arXiv:2008.08414
  url: https://arxiv.org/abs/2008.08414
config:
  dl4miceverywhere:
    cuda_version: 11.8.0
    cudnn_version: 8.6.0.163
    description: DecoNoising_2D_DL4Mic is the conversion of the CellPose 2D notebook from ZeroCostDL4Mic.
    dl4miceverywhere_version: 2.0.0
    docker_hub_image: deconoising_2d_zerocostdl4mic-z1.14.1-d2.0.0
    notebook_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/DecoNoising_2D_ZeroCostDL4Mic.ipynb
    notebook_version: 1.14.1
    python_version: '3.9'
    requirements_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/requirements_files/DecoNoising_2D_requirements_simple.txt
    sections_to_remove: 2. 6.3.
    ubuntu_version: '22.04'
covers:
- https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/Images/DecoNoising_notebook.png
description: Self-supervised denoising of 2D images. DecoNoising 2D is deep-learning method that can be used to denoise 2D microscopy images. By running this notebook, you can train your own network and denoise your images. Note - visit the ZeroCostDL4Mic wiki to check the original publications this network is based on and make sure you cite these.
documentation: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/README.md
download_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/DecoNoising_2D_ZeroCostDL4Mic.ipynb
git_repo: https://github.com/HenriquesLab/ZeroCostDL4Mic
id: Notebook_DecoNoising_2D_ZeroCostDL4Mic
links:
- Notebook Preview
- Dataset_Noise2Void_2D_ZeroCostDL4Mic
- Dataset_Noise2Void_2D_subtilis_DeepBacs
- Dataset_Noisy_Nuclei_ZeroCostDL4Mic
- Dataset_CARE_2D_coli_DeepBacs
name: DecoNoising (2D) - ZeroCostDL4Mic
tags:
- colab
- notebook
- DecoNoising
- denoising
- ZeroCostDL4Mic
- 2D
- dl4miceverywhere
type: application
version: 1.14.1
