authors:
- Lucas von Chamier and the ZeroCostDL4Mic Team
badges:
- icon: https://colab.research.google.com/assets/colab-badge.svg
  label: Open in Colab
  url: https://colab.research.google.com/github/HenriquesLab/ZeroCostDL4Mic/blob/master/Colab_notebooks/CARE_2D_ZeroCostDL4Mic.ipynb
cite:
- doi: https://doi.org/10.1038/s41467-021-22518-0
  text: von Chamier, L., Laine, R.F., Jukkala, J. et al. Democratising deep learning for microscopy with ZeroCostDL4Mic. Nat Commun 12, 2276 (2021). https://doi.org/10.1038/s41467-021-22518-0
- doi: https://doi.org/10.1038/s41592-018-0216-7
  text: "Weigert, M., Schmidt, U., Boothe, T. et al. Content-aware image restoration: pushing the limits of fluorescence microscopy. Nat Methods 15, 1090\u20131097 (2018). https://doi.org/10.1038/s41592-018-0216-7"
config:
  dl4miceverywhere:
    cuda_version: 11.8.0
    cudnn_version: 8.6.0.163
    description: CARE_2D_DL4Mic is the conversion of the 2D CARE from ZeroCostDL4Mic.
    dl4miceverywhere_version: 2.0.0
    docker_hub_image: care_2d_zerocostdl4mic-z1.15.2-d2.0.0
    notebook_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/CARE_2D_ZeroCostDL4Mic.ipynb
    notebook_version: 1.15.2
    python_version: '3.10'
    requirements_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/requirements_files/CARE_2D_requirements_simple.txt
    sections_to_remove: 1.1. 1.2. 2. 6.3.
    ubuntu_version: '22.04'
covers:
- https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/Images/CARE2D_notebook.png
- https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/Images/CARE2D_notebook_2.png
- https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/Images/CARE2D_notebook_3.png
description: Supervised restoration of 2D images. CARE is a neural network capable of image restoration from corrupted bio-images, first published in 2018 by Weigert et al. in Nature Methods. The network allows image denoising and resolution improvement in 2D and 3D images, in a supervised training manner. The function of the network is essentially determined by the set of images provided in the training dataset. For instance, if noisy images are provided as input and high signal-to-noise ratio images are provided as targets, the network will perform denoising. Note - visit the ZeroCostDL4Mic wiki to check the original publications this network is based on and make sure you cite these.
documentation: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/README.md
download_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/CARE_2D_ZeroCostDL4Mic.ipynb
git_repo: https://github.com/HenriquesLab/ZeroCostDL4Mic
id: Notebook_CARE_2D_ZeroCostDL4Mic
links:
- Notebook Preview
- Dataset_CARE_2D_ZeroCostDL4Mic
- Dataset_Noisy_Nuclei_ZeroCostDL4Mic
- Dataset_CARE_2D_coli_DeepBacs
- Dataset_fnet_DeepBacs
name: CARE (2D) - ZeroCostDL4Mic
tags:
- colab
- notebook
- CARE
- denoising
- ZeroCostDL4Mic
- 2D
- dl4miceverywhere
type: application
version: 1.15.2
