authors:
- Amin Rezaei, Guillaume Jacquemet and the ZeroCostDL4Mic Team
badges:
- icon: https://colab.research.google.com/assets/colab-badge.svg
  label: Open in Colab
  url: https://colab.research.google.com/github/HenriquesLab/ZeroCostDL4Mic/blob/master/Colab_notebooks/EmbedSeg_2D_ZeroCostDL4Mic.ipynb
cite:
- doi: https://doi.org/10.1038/s41467-021-22518-0
  text: von Chamier, L., Laine, R.F., Jukkala, J. et al. Democratising deep learning for microscopy with ZeroCostDL4Mic. Nat Commun 12, 2276 (2021). https://doi.org/10.1038/s41467-021-22518-0
- text: Manan Lalit, Pavel Tomancak, Florian Jug. Embedding-based Instance Segmentation in Microscopy. arXiv:2101.10033.
  url: https://arxiv.org/abs/2101.10033
config:
  dl4miceverywhere:
    cuda_version: 11.7.1
    cudnn_version: 8.6.0.163
    description: EmbedSeg_2D_DL4Mic is the conversion of the 2D EmbedSeg from ZeroCostDL4Mic.
    dl4miceverywhere_version: 2.0.0
    docker_hub_image: embedseg_2d_zerocostdl4mic-z1.15.0-d2.0.0
    notebook_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/EmbedSeg_2D_ZeroCostDL4Mic.ipynb
    notebook_version: 1.15.0
    python_version: '3.9'
    requirements_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/requirements_files/EmbedSeg_2D_requirements_simple.txt
    sections_to_remove: 1.0. 1.1. 2.
    ubuntu_version: '22.04'
covers:
- https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/Images/2D_Stardist_notebook.png
description: Instance segmentation of 2D images. EmbedSeg 2D is a deep-learning method that can be used to segment object from bioimages and was first published by Lalit et al. in 2021, on arXiv.
documentation: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/README.md
download_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/EmbedSeg_2D_ZeroCostDL4Mic.ipynb
git_repo: https://github.com/HenriquesLab/ZeroCostDL4Mic
id: Notebook_EmbedSeg_2D_ZeroCostDL4Mic
links:
- Notebook Preview
- Dataset_StarDist_2D_ZeroCostDL4Mic_2D
- Dataset_StarDist_Fluo_ZeroCostDL4Mic
- Dataset_StarDist_brightfield_ZeroCostDL4Mic
- Dataset_StarDist_brightfield2_ZeroCostDL4Mic
- Dataset_StarDist_fluo2_ZeroCostDL4Mic
name: EmbedSeg (2D) - ZeroCostDL4Mic
tags:
- colab
- notebook
- EmbedSeg
- Segmentation
- ZeroCostDL4Mic
- dl4miceverywhere
type: application
version: 1.15.0
