authors:
- "Daniel Krentzel and Estibaliz G\xF3mez de Mariscal andthe ZeroCostDL4Mic Team"
badges:
- icon: https://colab.research.google.com/assets/colab-badge.svg
  label: Open in Colab
  url: https://colab.research.google.com/github/HenriquesLab/ZeroCostDL4Mic/blob/master/Colab_notebooks/U-Net_3D_ZeroCostDL4Mic.ipynb
cite:
- doi: https://doi.org/10.1038/s41467-021-22518-0
  text: von Chamier, L., Laine, R.F., Jukkala, J. et al. Democratising deep learning for microscopy with ZeroCostDL4Mic. Nat Commun 12, 2276 (2021). https://doi.org/10.1038/s41467-021-22518-0
- text: "\xD6zg\xFCn \xC7i\xE7ek, Ahmed Abdulkadir, Soeren S. Lienkamp, Thomas Brox, Olaf Ronneberger. 3D U-Net: Learning Dense Volumetric Segmentation from Sparse Annotation. https://arxiv.org/abs/1606.06650"
  url: https://arxiv.org/abs/1606.06650
config:
  dl4miceverywhere:
    cuda_version: 11.8.0
    cudnn_version: 8.6.0.163
    description: U-Net_3D_DL4Mic is the conversion of the 3D U-Net from ZeroCostDL4Mic.
    dl4miceverywhere_version: 2.0.0
    docker_hub_image: u-net_3d_zerocostdl4mic-z2.1.3-d2.0.0
    notebook_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/U-Net_3D_ZeroCostDL4Mic.ipynb
    notebook_version: 2.1.3
    python_version: '3.10'
    requirements_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/requirements_files/3D_UNet_requirements_simple.txt
    sections_to_remove: 1.1. 1.2. 2. 6.2.
    ubuntu_version: '22.04'
covers:
- https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/Images/3D_Unet_notebook.png
description: "3D binary segmentation. The 3D U-Net was first introduced by \xC7i\xE7ek et al for learning dense volumetric segmentations from sparsely annotated ground-truth data building upon the original U-Net architecture by Ronneberger et al. Note - visit the ZeroCostDL4Mic wiki to check the original publications this network is based on and make sure you cite these."
documentation: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/README.md
download_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/U-Net_3D_ZeroCostDL4Mic.ipynb
git_repo: https://github.com/HenriquesLab/ZeroCostDL4Mic
id: Notebook_U-Net_3D_ZeroCostDL4Mic
links:
- Notebook Preview
name: U-Net (3D) - ZeroCostDL4Mic
tags:
- colab
- notebook
- U-Net
- segmentation
- ZeroCostDL4Mic
- 3D
- dl4miceverywhere
type: application
version: 2.1.3
