authors:
- "Estibaliz G\xF3mez de Mariscal and the ZeroCostDL4Mic team"
badges:
- icon: https://colab.research.google.com/assets/colab-badge.svg
  label: Open in Colab
  url: https://colab.research.google.com/github/HenriquesLab/ZeroCostDL4Mic/blob/master/Colab_notebooks/U-Net_2D_Multilabel_ZeroCostDL4Mic.ipynb
cite:
- doi: https://doi.org/10.1038/s41467-021-22518-0
  text: von Chamier, L., Laine, R.F., Jukkala, J. et al. Democratising deep learning for microscopy with ZeroCostDL4Mic. Nat Commun 12, 2276 (2021). https://doi.org/10.1038/s41467-021-22518-0
- text: 'Olaf Ronneberger, Philipp Fischer, Thomas Brox. U-Net: Convolutional Networks for Biomedical Image Segmentation. arXiv:1505.04597. https://arxiv.org/abs/1505.04597'
  url: https://arxiv.org/abs/1505.04597
config:
  dl4miceverywhere:
    cuda_version: 11.8.0
    cudnn_version: 8.6.0.163
    description: U-Net_2D_Multilabel_DL4Mic is the conversion of the 2D U-Net Multilabel from ZeroCostDL4Mic.
    dl4miceverywhere_version: 2.0.0
    docker_hub_image: u-net_2d_multilabel_zerocostdl4mic-z2.1.2-d2.0.0
    notebook_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/U-Net_2D_Multilabel_ZeroCostDL4Mic.ipynb
    notebook_version: 2.1.2
    python_version: '3.10'
    requirements_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/requirements_files/2D_UNet_multilabel_requirements_simple.txt
    sections_to_remove: 1.1. 1.2. 2. 6.2.
    ubuntu_version: '22.04'
covers:
- https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Wiki_files/UNet_Multilabel_example.png
- https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Wiki_files/UNet-multilabel-example-zoom.png
description: 2D semantic segmentation. U-Net is an encoder-decoder architecture originally used for image segmentation. The first half of the U-Net architecture is a downsampling convolutional neural network which acts as a feature extractor from input images. The other half upsamples these results and restores an image by combining results from downsampling with the upsampled images. Note - visit the ZeroCostDL4Mic wiki to check the original publications this network is based on and make sure you cite these.
documentation: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/README.md
download_url: https://colab.research.google.com/github/HenriquesLab/ZeroCostDL4Mic/blob/master/Colab_notebooks/U-Net_2D_Multilabel_ZeroCostDL4Mic.ipynb
format_version: 0.2.3
git_repo: https://github.com/HenriquesLab/ZeroCostDL4Mic
id: Notebook_U-Net_2D_multilabel_ZeroCostDL4Mic
links:
- Notebook Preview
- Dataset_U-Net_2D_multilabel_DeepBacs
name: U-Net (2D) multilabel segmentation - ZeroCostDL4Mic
tags:
- colab
- notebook
- u-net
- segmentation
- semantic-segmentation
- multilabel
- ZeroCostDL4Mic
- 2D
- dl4miceverywhere
type: application
version: 2.1.2
