authors:
- Guillaume Jacquemet and the ZeroCostDL4Mic Team
badges:
- icon: https://colab.research.google.com/assets/colab-badge.svg
  label: Open in Colab
  url: https://colab.research.google.com/github/HenriquesLab/ZeroCostDL4Mic/blob/master/Colab_notebooks/StarDist_3D_ZeroCostDL4Mic.ipynb
cite:
- doi: https://doi.org/10.1038/s41467-021-22518-0
  text: von Chamier, L., Laine, R.F., Jukkala, J. et al. Democratising deep learning for microscopy with ZeroCostDL4Mic. Nat Commun 12, 2276 (2021). https://doi.org/10.1038/s41467-021-22518-0
- text: "Martin Weigert, Uwe Schmidt, Robert Haase, Ko Sugawara, Gene Myers. Star-convex Polyhedra for 3D Object Detection and Segmentation in Microscopy. \tarXiv. https://arxiv.org/abs/1908.03636"
  url: https://arxiv.org/abs/1908.03636
config:
  dl4miceverywhere:
    cuda_version: 11.8.0
    cudnn_version: 8.6.0.163
    description: StarDist_3D_DL4Mic is the conversion of the 3D StarDist from ZeroCostDL4Mic.
    dl4miceverywhere_version: 2.0.0
    docker_hub_image: stardist_3d_zerocostdl4mic-z1.15.3-d2.0.0
    notebook_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/StarDist_3D_ZeroCostDL4Mic.ipynb
    notebook_version: 1.15.3
    python_version: '3.10'
    requirements_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/requirements_files/StarDist_3D_requirements_simple.txt
    sections_to_remove: 1.1. 1.2. 2. 6.2.
    ubuntu_version: '22.04'
covers:
- https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/Images/StarDist_3D.png
description: 3D instance segmentation of oval objects (ie nuclei). StarDist is a deep-learning method that can be used to segment cell nuclei in 3D (xyz) images. Note - visit the ZeroCostDL4Mic wiki to check the original publications this network is based on and make sure you cite these.
documentation: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/README.md
download_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/StarDist_3D_ZeroCostDL4Mic.ipynb
git_repo: https://github.com/HenriquesLab/ZeroCostDL4Mic
id: Notebook_StarDist_3D_ZeroCostDL4Mic
links:
- Notebook Preview
name: StarDist (3D) - ZeroCostDL4Mic
tags:
- colab
- notebook
- StarDist
- segmentation
- ZeroCostDL4Mic
- 3D
- dl4miceverywhere
type: application
version: 1.15.3
