authors:
- Guillaume Jacquemet and the ZeroCostDL4Mic Team
badges:
- icon: https://colab.research.google.com/assets/colab-badge.svg
  label: Open in Colab
  url: https://colab.research.google.com/github/HenriquesLab/ZeroCostDL4Mic/blob/master/Colab_notebooks/pix2pix_ZeroCostDL4Mic.ipynb
cite:
- doi: https://doi.org/10.1038/s41467-021-22518-0
  text: von Chamier, L., Laine, R.F., Jukkala, J. et al. Democratising deep learning for microscopy with ZeroCostDL4Mic. Nat Commun 12, 2276 (2021). https://doi.org/10.1038/s41467-021-22518-0
- text: Phillip Isola, Jun-Yan Zhu, Tinghui Zhou, Alexei A. Efros. Image-to-Image Translation with Conditional Adversarial Networks. arXiv:1611.07004.
  url: https://arxiv.org/abs/1611.07004
config:
  dl4miceverywhere:
    cuda_version: 11.8.0
    cudnn_version: 8.6.0.163
    description: pix2pix_DL4Mic is the conversion of the pix2pix from ZeroCostDL4Mic.
    dl4miceverywhere_version: 2.0.0
    docker_hub_image: pix2pix_zerocostdl4mic-z1.17.1-d2.0.0
    notebook_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/pix2pix_ZeroCostDL4Mic.ipynb
    notebook_version: 1.17.1
    python_version: '3.8'
    requirements_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/requirements_files/pix2pix_requirements_simple.txt
    sections_to_remove: 2. 6.3.
    ubuntu_version: '22.04'
covers:
- https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/Images/pix2pix_notebook_2.png
- https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/Images/pix2pix_notebook.png
description: Paired image-to-image translation of 2D images. pix2pix is a deep-learning method that can be used to translate one type of images into another. While pix2pix can potentially be used for any type of image-to-image translation, we demonstrate that it can be used to predict a fluorescent image from another fluorescent image. Note - visit the ZeroCostDL4Mic wiki to check the original publications this network is based on and make sure you cite these.
documentation: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/BioimageModelZoo/README.md
download_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/pix2pix_ZeroCostDL4Mic.ipynb
git_repo: https://github.com/HenriquesLab/ZeroCostDL4Mic
id: Notebook_pix2pix_2D_ZeroCostDL4Mic
links:
- Notebook Preview
- Dataset_pix2pix_ZeroCostDL4Mic
name: pix2pix (2D) - ZeroCostDL4Mic
tags:
- colab
- notebook
- pix2pix
- ZeroCostDL4Mic
- 2D
- dl4miceverywhere
type: application
version: 1.17.2
